dataset_name: casme
train_split: ['validation']
exam_split: ['valid']
val_split: ['test']
dataset: {
  csv_file: /data2/zyzhang/MEGC/MEGC_2024_code/labels/cas(me)_new.csv,
  feat_folder: /data2/zyzhang/dataset/CAS_feature_train,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 2,
  input_dim: 1408,
  feat_stride: 2,
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
}
model: {
  fpn_type: fpn,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 19,
}
opt: {
  learning_rate: 0.0001,
  epochs: 30,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: output/
